import type { Placement } from './types';

export const placements: Placement[] = [
  {
    id: 'place001',
    companyName: 'Innovatech',
    companyLogoUrl: 'https://picsum.photos/seed/innovatech/100/100',
    role: 'Software Engineer Intern',
    type: 'Internship',
    location: 'Remote',
    description: 'Work on cutting-edge AI projects and develop scalable web applications. Gain hands-on experience with our engineering team.',
    tags: ['AI', 'Web Dev', 'Python'],
  },
  {
    id: 'place002',
    companyName: 'QuantumLeap',
    companyLogoUrl: 'https://picsum.photos/seed/quantumleap/100/100',
    role: 'Data Analyst',
    type: 'Full-time',
    location: 'New York, NY',
    description: 'Analyze large datasets to extract meaningful insights and support data-driven decision making across the company.',
    tags: ['Data Analysis', 'SQL', 'Tableau'],
  },
  {
    id: 'place003',
    companyName: 'CyberGuard',
    companyLogoUrl: 'https://picsum.photos/seed/cyberguard/100/100',
    role: 'Cybersecurity Intern',
    type: 'Internship',
    location: 'Austin, TX',
    description: 'Assist in monitoring security infrastructure, identifying threats, and contributing to the development of security protocols.',
    tags: ['Security', 'Networking', 'Linux'],
  },
  {
    id: 'place004',
    companyName: 'NextGen Solutions',
    companyLogoUrl: 'https://picsum.photos/seed/nextgen/100/100',
    role: 'Junior Frontend Developer',
    type: 'Full-time',
    location: 'Remote',
    description: 'Join our frontend team to build responsive and user-friendly interfaces for our flagship products using React and TypeScript.',
    tags: ['Frontend', 'React', 'UI/UX'],
  },
   {
    id: 'place005',
    companyName: 'HealthCo',
    companyLogoUrl: 'https://picsum.photos/seed/healthco/100/100',
    role: 'Product Management Intern',
    type: 'Internship',
    location: 'San Francisco, CA',
    description: 'Work with product managers to define product roadmaps, conduct market research, and write specifications for new features.',
    tags: ['Product', 'Strategy', 'Healthcare'],
  },
   {
    id: 'place006',
    companyName: 'EcoVenture',
    companyLogoUrl: 'https://picsum.photos/seed/ecoventure/100/100',
    role: 'Sustainability Analyst',
    type: 'Full-time',
    location: 'Boston, MA',
    description: 'Help companies improve their environmental impact by analyzing sustainability data and creating actionable reports.',
    tags: ['Sustainability', 'Research', 'ESG'],
  },
];
